### ISSUE TITLE
Adding initial scout

### ISSUE THREAD

**Issue by cfreeman** [MeasureTheFuture/mothership_beta#6]
_What I did_

With an empty / fresh install. I visited the admin page `http://192.168.42.1/admin/` and pressed 'add' in the scouts row of the admin table. 

_What I saw_

A form requesting 'ip address' and 'name' for the new scout.

_What I expected._

A form requesting 'uuid' and 'name' for the new scout. The uuid is the key/identifier/authorisation used for the scout. While the scout will notify the mothership of it's IP address via the health heartbeat API (see below). 

The scout IP address may/will change, as it is automatically assigned via DHCP running on the mothership. So the scout automatically notifies the mothership of any changes. 

```
    POST http://moth.er.sh.ip/scout/heartbeat
    This is a MIME multipart message with an attached file (file:heartbeat.json) containing:
    {
        "UUID":"59ef7180-f6b2-4129-99bf-970eb4312b4b",  // Unique identifier of scout.
        "Version":"0.1",                                // Transmission protocol version.
        "Health":{
            "IpAddress":"10.1.1.1",                     // Current IP address of the scout.
            "CPU":0.4,                                  // Current CPU load, 0.0 - no load.
            "Memory":0.1,                               // Current Memory usage, 0.0 - not used, 1.0 all used.
            "TotalMemory":1233312.0,                    // Total Memory available in bytes.
            "Storage":0.1                               // Current Storage usage, 0.0 - not used, 1.0 all full.
        }
    }

    Within the request header is the following key "Mothership-Authorization", it
    contains the UUID of the scout.
```

**Comment by thatandromeda** [comment]
This is not my intended method for adding Scouts. My expectation is that:

1. The Scout will identify itself to the Mothership on startup;
2. The Mothership will then extract relevant data from the Scout's transmissions;
3. Users will use the web interface to add metadata that can't be harvested from the Scout (like a human-readable name).

I have added `docs/user.md` which covers this. I will also
1. make sure the mothership handles the newer UUID API behavior
1. Edit the admin site to avoid giving users direct access to properties not intended to be directly assigned.

**Comment by cfreeman** [comment]
This is all awesome.

At the moment, the scout is identifying itself with the mothership:

2016-05-15 04:21:15,379 WARNING mothership_beta.scout_api.views[post]:
Received JSON data for a nonexistent scout: {u'Version': u'0.1', u'Health':
{u'TotalMemory': 1006694400.0, u'Storage': 0.8843664, u'IpAddress':
u'192.168.42.21', u'CPU': 0.34000000000000002, u'Memory':
0.065401286000000003}, u'UUID': u'd7873b37-8b48-49a4-a058-bff7faa33b7b'}

I was struggling to figure out how to tell the mothership to upgrade it
from a 'nonexistent' to 'existent'. I couldn't figure out how to say. Yep.
This scout is authorised / validated.
